# -*- coding: utf-8 -*-
"""Orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6qAITJWRc_NSJZjIHQ5vjr07lgAQhJn
"""

A=2
B=3
C=2+3
print(C)

"""Example of String"""

Greetings= 'Advice na, pror'
print(Greetings)